/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyForm;



import MyClass.Peminjaman;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.io.File;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author meone
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    
    MyClass.Activity a = new MyClass.Activity();
    MyClass.centerText center = new MyClass.centerText();
    private List<Peminjaman> list = new ArrayList<>();
    
    public AdminForm() {
        initComponents();
    }
    
    public void displayName(String nama){
        NamaDisplay.setText(nama);
    }
    
    private void getDataPeminjaman(){
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) TableCalender.getModel();
        try{
            MyClass.PeminjamanSQL sql = new MyClass.PeminjamanSQLImpl();
            list = sql.getDataPeminjaman();
            
            for (Peminjaman obj : list){
                model.addRow(new Object[]{obj.getKode(), obj.getJudul(), obj.getNama(), obj.getTdate(), obj.getPdate()});
            }
            
        }catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal Mengambil Data!!");
        }
    }
    
    public void fillTable(String date){
        
        //add to table
        a.FillToTableRiwayat(TableCalender, date);
        
        //Set VAlue to Center
        for (int i = 0; i < TableCalender.getColumnCount(); i++){
            TableCalender.getColumnModel().getColumn(i).setCellRenderer(center);
        }
        
        //set Tbale Header to Center
        JTableHeader header = TableCalender.getTableHeader();
        ((DefaultTableCellRenderer)header.getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        
        //Set Column Width
        TableCalender.getColumnModel().getColumn(0).setPreferredWidth(70); //Kolom Kode Buku
        TableCalender.getColumnModel().getColumn(1).setPreferredWidth(200); // Kolom Judul Buku
        TableCalender.getColumnModel().getColumn(2).setPreferredWidth(150); // Kolon Pengarang
        TableCalender.getColumnModel().getColumn(3).setPreferredWidth(100); // Kolom Penerbit
        TableCalender.getColumnModel().getColumn(4).setPreferredWidth(100); // Kolom Status
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Calender = new com.toedter.calendar.JCalendar();
        jLabel4 = new javax.swing.JLabel();
        backToLogin = new javax.swing.JLabel();
        BacktoLogin = new javax.swing.JLabel();
        SearchButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCalender = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NamaDisplay = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        InventoryBook = new javax.swing.JLabel();
        InventoryBookLogo = new javax.swing.JLabel();
        report = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(189, 195, 199));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(108, 122, 137));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Perpustakaan Lite");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 630, 50));

        jLabel5.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/DashboardLogolibrary.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 10));

        Calender.setBackground(new java.awt.Color(0, 0, 0));
        Calender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)));
        Calender.setForeground(new java.awt.Color(51, 51, 51));
        Calender.setDecorationBackgroundColor(new java.awt.Color(189, 195, 199));
        Calender.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        Calender.setWeekOfYearVisible(false);
        Calender.setWeekdayForeground(new java.awt.Color(108, 122, 137));
        Calender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalenderMouseClicked(evt);
            }
        });
        jPanel2.add(Calender, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 580, 420));

        jLabel4.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Riwayat ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 80));

        backToLogin.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        backToLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backToLogin.setText("Back to Login");
        backToLogin.setToolTipText("");
        backToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToLoginMouseClicked(evt);
            }
        });
        jPanel2.add(backToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 670, 60));

        BacktoLogin.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        BacktoLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BacktoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/Before[32px].png"))); // NOI18N
        BacktoLogin.setToolTipText("");
        BacktoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BacktoLoginMouseClicked(evt);
            }
        });
        jPanel2.add(BacktoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, -1, 60));

        SearchButton1.setBackground(new java.awt.Color(108, 122, 137));
        SearchButton1.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        SearchButton1.setText("Search");
        SearchButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)));
        SearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(SearchButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 100, 35));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        TableCalender.setBackground(new java.awt.Color(189, 195, 199));
        TableCalender.setFont(new java.awt.Font("Bitstream Charter", 0, 14)); // NOI18N
        TableCalender.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Buku", "Judul Buku", "Nama", "T.Peminjaman", "T.Pengembalian"
            }
        ));
        TableCalender.setRowHeight(40);
        TableCalender.getTableHeader().setResizingAllowed(false);
        TableCalender.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TableCalender);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 650, 420));

        jSeparator2.setForeground(new java.awt.Color(108, 122, 137));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 700, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/UserProfile.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, -1, 60));

        jLabel6.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText(" Peminjaman");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 700, 80));

        NamaDisplay.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        NamaDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NamaDisplay.setText("jLabel2");
        jPanel1.add(NamaDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 0, 300, 60));

        jSeparator3.setForeground(new java.awt.Color(108, 122, 137));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 700, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/UserProfile.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, -1, 60));

        InventoryBook.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        InventoryBook.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InventoryBook.setText("Inventory Book");
        InventoryBook.setToolTipText("");
        InventoryBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryBookMouseClicked(evt);
            }
        });
        jPanel1.add(InventoryBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 670, 60));

        InventoryBookLogo.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        InventoryBookLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InventoryBookLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/Next[32px].png"))); // NOI18N
        InventoryBookLogo.setToolTipText("");
        InventoryBookLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryBookLogoMouseClicked(evt);
            }
        });
        jPanel1.add(InventoryBookLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 646, -1, 55));

        report.setBackground(new java.awt.Color(108, 122, 137));
        report.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        report.setText("iReport");
        report.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)));
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        jPanel1.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 100, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginMouseClicked
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToLoginMouseClicked

    private void BacktoLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BacktoLoginMouseClicked
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BacktoLoginMouseClicked

    private void InventoryBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBookMouseClicked
        // TODO add your handling code here:
        InventoryBook IB = new InventoryBook();
        IB.setVisible(true);
        IB.displayName(NamaDisplay.getText());
        this.dispose();
    }//GEN-LAST:event_InventoryBookMouseClicked

    private void InventoryBookLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBookLogoMouseClicked
        // TODO add your handling code here:
        InventoryBook IB = new InventoryBook();
        IB.setVisible(true);
        IB.displayName(NamaDisplay.getText());
        this.dispose();
    }//GEN-LAST:event_InventoryBookLogoMouseClicked

    private void CalenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalenderMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        String date = dt.format(Calender.getDate());
        JOptionPane.showMessageDialog(null, date);
    }//GEN-LAST:event_CalenderMouseClicked

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        TableCalender.setModel(new DefaultTableModel(null, new Object[]{"Kode Buku", "Judul Buku", "Pengarang", "Penerbit", "Status"}));
        getDataPeminjaman();
        try {
            // TODO add your handling code here:
            String path = "src/MyForm/Laporan.jrxml";
                        
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(list);
            File file = new File(path);
            JasperDesign jDesign = JRXmlLoader.load(file);
            
            
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, dataSource);
            
            JasperViewer.viewReport(jPrint, false);
            
            
        } catch (JRException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reportActionPerformed

    private void SearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        String date = dt.format(Calender.getDate());
        TableCalender.setModel(new DefaultTableModel(null, new Object[]{"Kode Buku", "Judul Buku", "Pengarang", "Penerbit", "Status"}));
        fillTable(date);
    }//GEN-LAST:event_SearchButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BacktoLogin;
    private com.toedter.calendar.JCalendar Calender;
    private javax.swing.JLabel InventoryBook;
    private javax.swing.JLabel InventoryBookLogo;
    private javax.swing.JLabel NamaDisplay;
    private javax.swing.JButton SearchButton1;
    private javax.swing.JTable TableCalender;
    private javax.swing.JLabel backToLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton report;
    // End of variables declaration//GEN-END:variables
}
