/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyForm;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author meone
 */
public class InventoryBook extends javax.swing.JFrame {

    /**
     * Creates new form InventoryBook
     */
    
    MyClass.Activity a = new MyClass.Activity();
    MyClass.centerText center = new MyClass.centerText();
    
    public InventoryBook() {
        initComponents();
    }
    
    public void displayName(String nama){
        NamaDisplay.setText(nama);
    }
    
    public boolean validateText(){
        if (kodeBuku.getText().trim().isEmpty() || judulBuku.getText().trim().isEmpty() || pengarang.getText().trim().isEmpty() 
                || penerbit.getText().trim().isEmpty() || Status.getItemAt(Status.getSelectedIndex()).equals("-")){
            JOptionPane.showMessageDialog(null, "Tolong isi Semua Data!!", "Failed", 2);
            return false;
        }else{
            return true;
        }
    }
    
    public void fillTable(){
        
        //add to table
        a.FillToTableInventory(TableInventory);
        
        //Set VAlue to Center
        for (int i = 0; i < TableInventory.getColumnCount(); i++){
            TableInventory.getColumnModel().getColumn(i).setCellRenderer(center);
        }
        
        //set Tbale Header to Center
        JTableHeader header = TableInventory.getTableHeader();
        ((DefaultTableCellRenderer)header.getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        
        //Set Column Width
        TableInventory.getColumnModel().getColumn(0).setPreferredWidth(70); //Kolom Kode Buku
        TableInventory.getColumnModel().getColumn(1).setPreferredWidth(200); // Kolom Judul Buku
        TableInventory.getColumnModel().getColumn(2).setPreferredWidth(150); // Kolon Pengarang
        TableInventory.getColumnModel().getColumn(3).setPreferredWidth(150); // Kolom Penerbit
        TableInventory.getColumnModel().getColumn(4).setPreferredWidth(70); // Kolom Status
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableInventory = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        backToLogin = new javax.swing.JLabel();
        BacktoLogin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        judulBuku = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pengarang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        penerbit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kodeBuku = new javax.swing.JTextField();
        EditButton = new javax.swing.JButton();
        NamaDisplay = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DeleteButton1 = new javax.swing.JButton();
        riwayat = new javax.swing.JLabel();
        Riwayatbutton = new javax.swing.JLabel();
        Status = new javax.swing.JComboBox<>();
        RefreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(189, 195, 199));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(108, 122, 137));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableInventory.setBackground(new java.awt.Color(108, 122, 137));
        TableInventory.setFont(new java.awt.Font("Bitstream Charter", 0, 14)); // NOI18N
        TableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Buku", "Judul Buku", "Pengarang", "Penerbit", "Status"
            }
        ));
        TableInventory.setRowHeight(40);
        TableInventory.getTableHeader().setResizingAllowed(false);
        TableInventory.getTableHeader().setReorderingAllowed(false);
        TableInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableInventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableInventory);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 560, 400));

        jLabel3.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Perpustakaan Lite");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 630, 50));

        jLabel5.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/DashboardLogolibrary.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 10));

        jLabel4.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Inventory ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 700, 80));

        backToLogin.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        backToLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backToLogin.setText("Back to Login");
        backToLogin.setToolTipText("");
        backToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToLoginMouseClicked(evt);
            }
        });
        jPanel2.add(backToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 670, 60));

        BacktoLogin.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        BacktoLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BacktoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/Before[32px].png"))); // NOI18N
        BacktoLogin.setToolTipText("");
        BacktoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BacktoLoginMouseClicked(evt);
            }
        });
        jPanel2.add(BacktoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, -1, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        jLabel6.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Kode Buku");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 140, -1));

        judulBuku.setBackground(new java.awt.Color(189, 195, 199));
        judulBuku.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        judulBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        jPanel1.add(judulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 470, 30));

        AddButton.setBackground(new java.awt.Color(189, 195, 199));
        AddButton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        AddButton.setText("Add");
        AddButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        AddButton.setContentAreaFilled(false);
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 150, 30));

        jLabel7.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Judul Buku");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 140, -1));

        jLabel8.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Pengarang");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 140, -1));

        pengarang.setBackground(new java.awt.Color(189, 195, 199));
        pengarang.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        pengarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        jPanel1.add(pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 470, 30));

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Penerbit");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 140, -1));

        penerbit.setBackground(new java.awt.Color(189, 195, 199));
        penerbit.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        penerbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        jPanel1.add(penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 470, 30));

        jLabel10.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Status");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 140, -1));

        kodeBuku.setBackground(new java.awt.Color(189, 195, 199));
        kodeBuku.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        kodeBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        jPanel1.add(kodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 470, 30));

        EditButton.setBackground(new java.awt.Color(189, 195, 199));
        EditButton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        EditButton.setText("Edit");
        EditButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        EditButton.setContentAreaFilled(false);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 150, 30));

        NamaDisplay.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        NamaDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NamaDisplay.setText("jLabel2");
        jPanel1.add(NamaDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 0, 300, 60));

        jSeparator2.setForeground(new java.awt.Color(108, 122, 137));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 700, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/UserProfile.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, -1, 60));

        jLabel11.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText(" Book");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 700, 80));

        DeleteButton1.setBackground(new java.awt.Color(189, 195, 199));
        DeleteButton1.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        DeleteButton1.setText("Delete");
        DeleteButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        DeleteButton1.setContentAreaFilled(false);
        DeleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 460, 150, 30));

        riwayat.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        riwayat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        riwayat.setText("Riwayat Peminjaman");
        riwayat.setToolTipText("");
        riwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatMouseClicked(evt);
            }
        });
        jPanel1.add(riwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 670, 60));

        Riwayatbutton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        Riwayatbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Riwayatbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/Next[32px].png"))); // NOI18N
        Riwayatbutton.setToolTipText("");
        Riwayatbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RiwayatbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(Riwayatbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 646, -1, 55));

        Status.setBackground(new java.awt.Color(189, 195, 199));
        Status.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Dipinjam", "Tidak Dpinjam" }));
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 470, -1));

        RefreshButton.setBackground(new java.awt.Color(189, 195, 199));
        RefreshButton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        RefreshButton.setText("Refresh");
        RefreshButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        RefreshButton.setContentAreaFilled(false);
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RefreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 460, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RiwayatbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiwayatbuttonMouseClicked
        // TODO add your handling code here:
        AdminForm rw = new AdminForm();
        rw.setVisible(true);
        rw.displayName(NamaDisplay.getText());
        this.dispose();
    }//GEN-LAST:event_RiwayatbuttonMouseClicked

    private void riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseClicked
        // TODO add your handling code here:
        AdminForm rw = new AdminForm();
        rw.setVisible(true);
        rw.displayName(NamaDisplay.getText());
        this.dispose();
    }//GEN-LAST:event_riwayatMouseClicked

    private void backToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginMouseClicked
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToLoginMouseClicked

    private void BacktoLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BacktoLoginMouseClicked
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BacktoLoginMouseClicked

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        
        if (validateText()){
            
            String kode = kodeBuku.getText().trim();
            String judul = judulBuku.getText().trim();
            String Pengarang = pengarang.getText().trim();
            String Penerbit = penerbit.getText().trim();
            String status = Status.getItemAt(Status.getSelectedIndex());

            a.InsertUpdateDelete('i', kode, judul, Pengarang, Penerbit, status);
        }
        
        kodeBuku.setText("");
        judulBuku.setText("");
        pengarang.setText("");
        penerbit.setText("");
        Status.setSelectedIndex(0);       
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
                
        if (validateText()){
            
            String kode = kodeBuku.getText().trim();
            String judul = judulBuku.getText().trim();
            String Pengarang = pengarang.getText().trim();
            String Penerbit = penerbit.getText().trim();
            String status = Status.getItemAt(Status.getSelectedIndex());

            a.InsertUpdateDelete('u', kode, judul, Pengarang, Penerbit, status);
        }
        
        kodeBuku.setText("");
        judulBuku.setText("");
        pengarang.setText("");
        penerbit.setText("");
        Status.setSelectedIndex(0);  
        
    }//GEN-LAST:event_EditButtonActionPerformed

    private void DeleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton1ActionPerformed
        // TODO add your handling code here:
        if (validateText()){
            String kode = kodeBuku.getText().trim();
            String judul = judulBuku.getText().trim();
            String Pengarang = pengarang.getText().trim();
            String Penerbit = penerbit.getText().trim();
            String status = Status.getItemAt(Status.getSelectedIndex());

            a.InsertUpdateDelete('d', kode, judul, Pengarang, Penerbit, status);
        }
        
        kodeBuku.setText("");
        judulBuku.setText("");
        pengarang.setText("");
        penerbit.setText("");
        Status.setSelectedIndex(0);  
        
    }//GEN-LAST:event_DeleteButton1ActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        TableInventory.setModel(new DefaultTableModel(null, new Object[]{"Kode Buku", "Judul Buku", "Pengarang", "Penerbit", "Status"}));
        fillTable();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            DefaultTableModel model = new DefaultTableModel();
            model = (DefaultTableModel) TableInventory.getModel();
            model.setRowCount(0);
            fillTable();
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void TableInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableInventoryMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) TableInventory.getModel();
        int index = TableInventory.getSelectedRow();
        
        kodeBuku.setText(model.getValueAt(index, 0).toString());
        judulBuku.setText(model.getValueAt(index, 1).toString());
        pengarang.setText(model.getValueAt(index, 2).toString());
        penerbit.setText(model.getValueAt(index, 3).toString());
        for (int i = 0; i < Status.getItemCount(); i++){
            if (model.getValueAt(index, 4).toString() == Status.getItemAt(i)){
                Status.setSelectedIndex(i);
            }
        }
    }//GEN-LAST:event_TableInventoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel BacktoLogin;
    private javax.swing.JButton DeleteButton1;
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel NamaDisplay;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JLabel Riwayatbutton;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JTable TableInventory;
    private javax.swing.JLabel backToLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField judulBuku;
    private javax.swing.JTextField kodeBuku;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField pengarang;
    private javax.swing.JLabel riwayat;
    // End of variables declaration//GEN-END:variables
}
