/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyForm;

import javax.swing.JOptionPane;

/**
 *
 * @author meone
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    
    MyClass.Activity active = new MyClass.Activity();
    
    public LoginForm() {
        initComponents();
    }
    
    public boolean validateText(){
        
        if(lUsernama.getText().trim().isEmpty() || lPassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tolong isi Username dan Password Anda!!", "Failed", 2);
            return false;
        }else{
            return true;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Shutdown = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lUsernama = new javax.swing.JTextField();
        lPassword = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        RegisButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(189, 195, 199));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(108, 122, 137));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/libraryLogo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Perpustakaan Lite");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 700, 100));

        Shutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/LogOutIcon.png"))); // NOI18N
        Shutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShutdownMouseClicked(evt);
            }
        });
        jPanel2.add(Shutdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        jLabel3.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 700, 100));

        jLabel4.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 230, -1));

        jLabel6.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 230, -1));

        lUsernama.setBackground(new java.awt.Color(189, 195, 199));
        lUsernama.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        lUsernama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        jPanel1.add(lUsernama, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 320, 30));

        lPassword.setBackground(new java.awt.Color(189, 195, 199));
        lPassword.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        lPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        jPanel1.add(lPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 340, 320, 30));

        LoginButton.setBackground(new java.awt.Color(189, 195, 199));
        LoginButton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        LoginButton.setContentAreaFilled(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 390, 100, 30));

        RegisButton.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        RegisButton.setForeground(new java.awt.Color(0, 105, 146));
        RegisButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisButton.setText("Belum Memiliki Akun? Daftar Disini!");
        RegisButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisButtonMouseClicked(evt);
            }
        });
        jPanel1.add(RegisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 700, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String User = lUsernama.getText().trim();
        String Pass = lPassword.getText().trim();
        
        if(validateText()){
            String Nama = active.login(User, Pass);
            
            if(Nama.equals("")){
                lUsernama.setText("");
                lPassword.setText("");
            }else{
                if (Nama.equals("admin")){
                    InventoryBook IB = new InventoryBook();
                    IB.setVisible(true);
                    IB.displayName(Nama);
                    this.dispose();
                }else{
                    UserForm user = new UserForm();
                    user.setVisible(true);
                    user.displayName(Nama, User);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void RegisButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisButtonMouseClicked
        // TODO add your handling code here:
        RegisForm regis = new RegisForm();
        regis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisButtonMouseClicked

    private void ShutdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShutdownMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ShutdownMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel RegisButton;
    private javax.swing.JLabel Shutdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField lPassword;
    private javax.swing.JTextField lUsernama;
    // End of variables declaration//GEN-END:variables
}
