/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyForm;

import javax.swing.JOptionPane;

/**
 *
 * @author meone
 */
public class RegisForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisForm
     */
    
    MyClass.Activity regis = new MyClass.Activity();
    
    public RegisForm() {
        initComponents();
    }
    
    public boolean validateText(){
        if (rUsername.getText().isEmpty() || rPassword.getText().isEmpty() || rNama.getText().isEmpty() 
                || rAlamat.getText().isEmpty() || rTelepon.getText().isEmpty() || rProfile.getItemAt(rProfile.getSelectedIndex()).equals("-")){
            JOptionPane.showMessageDialog(null, "Tolong isi Username dan Password Anda!!", "Failed", 2);
            return false;
        }else{
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rUsername = new javax.swing.JTextField();
        rPassword = new javax.swing.JPasswordField();
        RegisButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rNama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rAlamat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rTelepon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rProfile = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(189, 195, 199));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(108, 122, 137));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/libraryLogo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Perpustakaan Lite");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 700, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        jLabel3.setFont(new java.awt.Font("Bitstream Charter", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Register");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 700, 100));

        jLabel6.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 230, -1));

        rUsername.setBackground(new java.awt.Color(189, 195, 199));
        rUsername.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        rUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        jPanel1.add(rUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 320, 30));

        rPassword.setBackground(new java.awt.Color(189, 195, 199));
        rPassword.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        rPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        jPanel1.add(rPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, 320, 30));

        RegisButton.setBackground(new java.awt.Color(189, 195, 199));
        RegisButton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        RegisButton.setText("Register");
        RegisButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        RegisButton.setContentAreaFilled(false);
        RegisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 500, 100, 30));

        LoginButton.setFont(new java.awt.Font("Bitstream Charter", 0, 15)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(0, 105, 146));
        LoginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginButton.setText("Sudah Memiliki Akun? Login Disini!");
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        jPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 700, 40));

        jLabel7.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 230, -1));

        jLabel8.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nama");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 230, -1));

        rNama.setBackground(new java.awt.Color(189, 195, 199));
        rNama.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        rNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        jPanel1.add(rNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 320, 30));

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Alamat");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 230, -1));

        rAlamat.setBackground(new java.awt.Color(189, 195, 199));
        rAlamat.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        rAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        jPanel1.add(rAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 320, 30));

        jLabel10.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Profile");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 230, -1));

        rTelepon.setBackground(new java.awt.Color(189, 195, 199));
        rTelepon.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        rTelepon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(108, 122, 137)));
        rTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rTeleponKeyTyped(evt);
            }
        });
        jPanel1.add(rTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 320, 30));

        jLabel11.setFont(new java.awt.Font("Bitstream Charter", 0, 22)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("No. HP");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 230, -1));

        rProfile.setBackground(new java.awt.Color(189, 195, 199));
        rProfile.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        rProfile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Siswa", "Mahasiswa", "Guru", "Dosen" }));
        jPanel1.add(rProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void RegisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisButtonActionPerformed
        // TODO add your handling code here:
        if (validateText()){
           
            String user = rUsername.getText();
            String pass = rPassword.getText();
            String nama = rNama.getText();
            String alamat = rAlamat.getText();
            String telepon = rTelepon.getText();
            String profile = rProfile.getItemAt(rProfile.getSelectedIndex());
            
            regis.register(user, pass, profile, nama, alamat, telepon);            
            
            rUsername.setText("");
            rPassword.setText("");
            rNama.setText("");
            rAlamat.setText("");
            rTelepon.setText("");
            rProfile.setSelectedIndex(0);            
        
        }
                
    }//GEN-LAST:event_RegisButtonActionPerformed

    private void rTeleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rTeleponKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_rTeleponKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginButton;
    private javax.swing.JButton RegisButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField rAlamat;
    private javax.swing.JTextField rNama;
    private javax.swing.JPasswordField rPassword;
    private javax.swing.JComboBox<String> rProfile;
    private javax.swing.JTextField rTelepon;
    private javax.swing.JTextField rUsername;
    // End of variables declaration//GEN-END:variables
}
